import "../styles/globals.css";
import { WalletProvider } from "../components/wallet/WalletProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
